{% set name = "ago" %}
{% set version = "0.0.92" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "81e838ef978a19f8a263e72e4ae75345b639943e9853b33c4572b04b1d6f01f9" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - ago

about:
  home: https://bitbucket.org/russellballestrini/ago/
  # No license file, just stated in README.rst
  license_file: README.rst
  license: Public Domain
  icense_family: OTHER
  summary: 'ago: Human readable timedeltas'
  dev_url: https://bitbucket.org/russellballestrini/ago/
  doc_url: https://bitbucket.org/russellballestrini/ago/

extra:
  recipe-maintainers:
    - pmlandwehr
