{% set name = "ago" %}
{% set version = "0.0.95" %}
{% set bundle = "tar.gz" %}
{% set hash = "d2010f5eac3df544ec48ec116102e068591a345b1a580f32973db8a505fca744" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - ago

about:
  home: https://bitbucket.org/russellballestrini/ago/
  # No license file, just stated in README.rst
  license_file: README.rst
  license: Public Domain
  license_family: OTHER
  summary: 'ago: Human readable timedeltas'
  dev_url: https://bitbucket.org/russellballestrini/ago/
  doc_url: https://bitbucket.org/russellballestrini/ago/

extra:
  recipe-maintainers:
    - pmlandwehr
