travis:
  secure:
    BINSTAR_TOKEN: M+FGM2qzJP14RZYmXSs3t2Tc311ALkluLMYyKbZrwLNMtpjnkekRIKXH7qtq8XVwVaLhJeAmiyyjcohjeOJrUiE8fK+c1pCSBpAtIIUEPQT9mPLXCLG1mzd+ZYYatzXZxnY6wJIry5QIJxiGrrQFxpijQiSgcBju7n+cYP3BlfcdZzmuVteAb886Wl4e2r2yYvEEjfAc12Pe4OpmF/l3S4+HSBccqP9GW4mYLCqgfFGC4qx/LHytIkM6IA7wjLs1y074ja2X3qpplG0ANg0ntPgdRp7mBI2x53zB8cTl1DDRAgZtH3BzUCNDvgCiExQ/wtST6RzBlpbrWtfx44GA5WeM9v8CwzUuQmV3t4/vbQiV7RT+Wc8/3M4kQLJhFWZdx+liRB9uGLld8G0kDo2l0CWt1fpNkBtOsuBQ9vPtmdplGpRjbMomGAm5yifEa54l3CvVUOBJ5DqZXmccbiSl/suqlTazaAJXokGblmEFqE/zqmTUexfGH7amlTgl+WYrhOhuKEGJcjzXHOdgt60WWDtHxfl31rFQS3xAYBl+rHl+nELlMNqndxCwurJXRaO/K8lmcaMix9MU62dWasdvuTu94ouWXu0RWLNgjaTD9OgNuK1lo24S9Tx4j2ZvBXDsFv3F1j1moDypbDs2jV3CEgTQwHK2rqF88Q95NLACtqo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
