travis:
  secure:
    BINSTAR_TOKEN: dKv77vOZtMYoiyZ6evzd7GpiIgPk8IAn8v1n2onK4NSxR73o9VcaCe35rmADufFZeJNmtq3OZ3XLHrwrtR/20uzaQl4Hb2XCJDqV+JB5MIaW+LYaceBtpEem9VdDpAO4/Wl7asvKnjpFjuB94WsT5wIKvVQqp5fQIFLWWC6cFYSRhbXaerh8aM2ElGCvXECcwIXO7UjCmaXPk2LZu/P+hKXFKhO/UWorDlkwURSYyKPUotYgk42Ip1wYn6tcjw9qbpz2BMKatXNoUN/BuWU/HHsv5ao/A3LyO1bXvgnsBKeQRztOghxOQ8kg3Gc3gB8/DSFVoFKCnuFYd3wFExY6J+VbIquI2n+UMaIYVDRGgFOLgU6I9GA905rJlULUXl0iOY1J7JgM+yNjdr5ydI4ULKg/sHsT1FujgazIetb4vXD0UYX11pWF/vzjhumkDuvbIArOSUXjBQT51Z3LewiN+5XvSFUP9GCMIDI2ElE5mqCYF8QJdqQQAkEYooWL3SafcxCmvHiOC6Ffh5xZ9HyOjq1OktGZmYzUsrf6iFb7e2oXCy3Hsoz38bvbz7+Jd6SyHUBxvIETMsECd0rgsj17DRGbeOwrCMoi95twX/l0wni0svNzMFfvH6hNj4aFk2Pa/ty2DAkEpHfxd5IXT2RqSC4Z/70pE0HxJxuXSdGgajs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
